<?php

/**
 * The module's name.
 */
define('DRUPAL_PLUS', 'drupal_plus');

/**
 * The module's path.
 */
define('DRUPAL_PLUS_PATH', drupal_get_path('module', 'drupal_plus'));

/**
 * The module's cache table.
 */
define('DRUPAL_PLUS_DB__CACHE', 'cache_drupal_plus');

module_load_include('inc', DRUPAL_PLUS, 'drupal_plus.cache');
module_load_include('inc', DRUPAL_PLUS, 'drupal_plus.functions');
module_load_include('inc', DRUPAL_PLUS, 'drupal_plus.invoke');
module_load_include('inc', DRUPAL_PLUS, 'drupal_plus.hooks');
module_load_include('inc', DRUPAL_PLUS, 'drupal_plus.registry');
module_load_include('inc', DRUPAL_PLUS, 'includes/drupal_plus.system');

/**
 * Implements hook_menu().
 */
function drupal_plus_menu() {
  $items                                  = array();
  $items['admin/config/drupal-plus']      = array(
    'title'            => 'Drupal plus',
    'description'      => 'Drupal plus',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path'        => drupal_get_path('module', 'system'),
    'file'             => 'system.admin.inc',
  );
  $items['admin/config/drupal-plus/test'] = array(
    'title'            => 'Drupal plus test page.',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'drupal_plus_test',
    'access arguments' => array('access site configuration'),
  );

  return $items;
}

/**
 * Test function.
 */
function drupal_plus_test() {

}

/**
 * Implements hook_admin_menu_cache_info().
 */
function drupal_plus_admin_menu_cache_info() {
  $caches[DRUPAL_PLUS] = array(
    'title'    => t('Drupal plus'),
    'callback' => 'drupal_plus_cc_all',
  );

  return $caches;
}

/**
 * Implements hook_flush_caches().
 */
function drupal_plus_flush_caches() {
  return array(DRUPAL_PLUS_DB__CACHE);
}

/**
 * Implements hook_permission_tpl_info().
 */
function drupal_plus_permission_tpl_info() {
  $info                              = array();
  $info['administer_module']         = array(
    'tpl'   => 'administer.%module%',
    'group' => 'system'
  );
  $info['add_any_bundle_entity']     = array(
    'tpl'   => 'add.any.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['edit_any_bundle_entity']    = array(
    'tpl'   => 'edit.any.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['edit_own_bundle_entity']    = array(
    'tpl'   => 'edit.own.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['delete_any_bundle_entity']  = array(
    'tpl'   => 'delete.own.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['delete_own_bundle_entity']  = array(
    'tpl'   => 'delete.own.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['view_any_bundle_entity']    = array(
    'tpl'   => 'view.any.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['view_own_bundle_entity']    = array(
    'tpl'   => 'view.own.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['publish_any_bundle_entity'] = array(
    'tpl'   => 'publish.any.%bundle%.%entity_type%',
    'group' => 'entities'
  );
  $info['publish_own_bundle_entity'] = array(
    'tpl'   => 'publish.own.%bundle%.%entity_type%',
    'group' => 'entities'
  );

  return $info;
}